git puanalyzer:
  # 여기서 특정 linter 규칙을 '경고(warning)'나 '에러(error)'로 강제로 지정
  errors:
    # 특정 규칙을 CI에서 실패를 유발하는 'error' 등급으로 격상
    unnecessary_import: error
    unused_import: info
    dead_code: error
    unused_field: info
    unused_element: info
    prefer_const_constructors: info
    prefer_const_declarations: info
    prefer_const_constructors_in_immutables: info
    prefer_const_literals_to_create_immutables: info
    always_specify_types: ignore
    prefer_relative_imports: error
    undefined_lint: ignore
    duplicate_import: error

linter:
  # 여기서 검사할 규칙 목록을 직접 관리
  rules:
    # 특정 규칙만 활성화하고, 나머지는 모두 무시
    - unnecessary_import
    - unused_import
    - dead_code
    - unused_field
    - unused_element
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - always_specify_types
    - prefer_relative_imports
