name: markit_place_front
description: "Final project Viwe Front"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # UI/Widget Dependencies
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.6
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  image_picker: ^1.1.2

  # State Management & HTTP
  flutter_riverpod: ^2.3.6
  http: ^1.1.0
  dio: ^5.2.0

  # Authentication
  google_sign_in: ^6.2.1
  flutter_naver_login: ^2.0.0

  # Local Storage & Logging
  flutter_secure_storage: ^8.0.0
  logger: ^1.3.0

  # Data & Utility
  intl: ^0.18.1
  validators: ^3.0.0

  # Real-time & Geolocation
  stomp_dart_client: ^2.1.3
  flutter_client_sse: ^2.0.3
  location: ^8.0.1
  flutter_naver_map: ^1.4.1+1
  flutter_compass: ^0.8.1
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1

  # Configuration
  flutter_dotenv: ^6.0.0

  # Other Dependencies
  path: ^1.8.3 # 버전 지정
  dotenv: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.1 # flutter_lints는 dev_dependencies에만 두는 것이 일반적입니다.

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/social/
    - .env


  fonts:
    - family: CookieRun
      fonts:
        - asset: assets/fonts/CookieRun Regular.otf
          weight: 400
        - asset: assets/fonts/CookieRun Bold.otf
          weight: 700
        - asset: assets/fonts/CookieRun Black.otf
          weight: 900
